name: DOODS2-amd64
version: '1'
slug: doods2-amd64
url: https://github.com/snowzach/hassio-addons/tree/master/doods2
description: DOODS V2 Object Detection API - Modern AMD64 Chipsets with AVX instructions.
webui: http://[HOST]:[PORT:8080]
arch:
- amd64
startup: services
map:
- share
usb: true
options:
  logger:
    level: info
  server:
    port: '8080'
    auth_key: ''
  doods.log: detections
  doods.boxes:
    enabled: true
    boxColor: "#00ff00"
    boxThickness: 1
    fontScale: 1.2
    fontColor: "#00ff00"
    fontThickness: 1
  doods.regions:
    enabled: true
    boxColor: "#ff00ff"
    boxThickness: 1
    fontScale: 1.2
    fontColor: "#ff00ff"
    fontThickness: 1
  doods.globals:
    enabled: true
    fontScale: 1.2
    fontColor: "#ffff00"
    fontThickness: 1
  doods.detectors:
    - name: default
      type: tflite
      modelFile: models/coco_ssd_mobilenet_v1_1.0_quant.tflite
      labelFile: models/coco_labels0.txt
    - name: tensorflow
      type: tensorflow
      modelFile: models/faster_rcnn_inception_v2_coco_2018_01_28.pb
      labelFile: models/coco_labels1.txt
    - name: pytorch
      type: pytorch
      modelFile: ultralytics/yolov5,yolov5s
schema:
  logger:
    level: str?
  server:
    port: port?
    auth_key: str?
  doods.boxes:
    enabled: bool
    boxColor: str
    boxThickness: float
    fontScale: float
    fontColor: str
    fontThickness: float
  doods.regions:
    enabled: bool
    boxColor: str
    boxThickness: float
    fontScale: float
    fontColor: str
    fontThickness: float
  doods.globals:
    enabled: bool
    fontScale: float
    fontColor: str
    fontThickness: float
  doods.detectors:
  - name: str
    type: str
    modelFile: str
    labelFile: str?
    hwAccel: bool?
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: DOODS2 port
